language: erlang
notifications:
  recipients:
    - eduardo@gurgel.me
otp_release:
  - 17.0
install: mix deps.get
before_install:
  - mkdir -p vendor/elixir
  - wget -q https://github.com/elixir-lang/elixir/releases/download/v0.14.1/Precompiled.zip && unzip -qq Precompiled.zip -d vendor/elixir
  - export PATH="$PWD/vendor/elixir/bin:$PATH"
  - export MIX_ENV=test
  - mix local.hex --force
  - rebar --version
script: mix test
services:
  - riak
